### ISSUE TITLE
Resizing location wrong with new bootstrap

### ISSUE THREAD

**Issue by virk** [turnermm/Dokuwiki-Nav-Overlay#6] opened 2018-02-18 10:55 UTC
I just installed the new bootstrap-template. It seems that the resize-location of the popup-window moves with the scrolling within this window and does not remain at its lower right edge (as it should be)

**Comment by turnermm** [comment] 2018-02-18 13:27
You will have to take that up with the author of bootstrap.  It is often the source of conflicts.

**Comment by virk** [comment] 2018-02-18 18:19
Thank you. I will leave a message to him :-)

**Comment by virk** [comment] 2018-02-19 06:46
I left on comment there but I just noticed that this behaviour also appears with dokuwiki-template. I spent two weeks for holidays (windsurfing); maybe I totally forgot, that it (resize-location-behaviour) was always like above described :-)

**Comment by turnermm** [comment] 2018-02-19 15:19
At the top of the window, the detach/attach link determines the behavior.  I just tested with the latest  bootstrap and had no problems.  Nor with the dokuwiki.  Try clearing the cache in both browser and wiki (just empty out data/cache).

**Comment by virk** [comment] 2018-02-20 06:27
Kindly have a look at the attached screenshot: The "point" (3 diagonal small lines), where to resize the window is no longer bottom right but has moved with the scrolling inside the overlay window. This is what I meant.

<img width="263" alt="overlay" src="https://user-images.githubusercontent.com/451702/36410046-27256490-160f-11e8-81b3-7a13d8db0146.png">

**Comment by turnermm** [comment] 2018-02-20 14:01
I've been aware of that.  The overlay window is a jQuery draggable object and jQuery sets the position of the grab icon.  It may be controllable, I'd have to check, the documentation is not clear.  It still works, it's just not where you expect it to be.

**Comment by turnermm** [comment] 2018-02-20 16:21
I've tried doing something about this for a while this morning and haven't had any success.  The drag icon is relative to the scrollbars.  Presumably it can be made relative to the mouse pointer but I haven't been successful with that.

**Comment by virk** [comment] 2018-02-20 21:38
I like that plugin much and most probably after my holidays I just forgot that it works like it does :-)

**Comment by turnermm** [comment] 2018-02-21 00:21
I might have a solution of sorts: 

https://github.com/turnermm/Dokuwiki-Nav-Overlay/archive/tmp.zip

The commit message more or less explains it:  `When detached from background,the resize handle disappears, when re-attached it reappears. The resize is retained`

Let me know what you think.

**Comment by virk** [comment] 2018-02-21 21:45
I just tested the tmp.zip: Unfortunately I do not understand the problem. From my point of view the overlay window should be a "normal" window with resize handle bottom right and with "scrollable" content.
The tmp-version you uploaded "only" makes the handle disappear, so cosmetically it looks better but function of resizing has gone now.
It seems like you coded the overlay-window by yourself. Can this overlay window not be made like a normal window; f.e. with close button top left, resize handle bottom right? Addiionally this window should reappear (with same size), where it was opened last time. It is just a question, I have absolutely no idea about coding this :-)

The window at github, where I am typing this text: Even, when I scroll the window, the resizing button remains bottom right.
I just read again your post from earlier, where you explained that "jQuery draggable object"…It seems not to be that easy :-)

**Comment by turnermm** [comment] 2018-02-22 18:43
A solution has been merged into the master distro which hides the resize handle when the mouse exits the overlay. 
> It seems like you coded the overlay-window by yourself

Not true.

**Comment by turnermm** [comment] 2018-02-25 17:08
Well.  Persistence seems to have  paid off.  Checout that latest master.

**Comment by turnermm** [comment] 2018-02-27 14:46
>  Unfortunately I do not understand the problem

The problem is that these things are not simple to  do and can be extremely time-consuming, and no one is getting paid to do this.

I've discarded the original approach for a new one:
https://github.com/turnermm/Dokuwiki-Nav-Overlay/archive/handles.zip

**Comment by turnermm** [comment] 2018-03-01 02:29
Merged

**Closed as completed by turnermm** 2018-03-01 02:29 UTC
